# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniil/Ping-Pong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniil/Ping-Pong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniil/Ping-Pong/CMakeFiles /home/daniil/Ping-Pong//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniil/Ping-Pong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PingPongRelease

# Build rule for target.
PingPongRelease: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PingPongRelease
.PHONY : PingPongRelease

# fast build rule for target.
PingPongRelease/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/build
.PHONY : PingPongRelease/fast

Ping_Pong/Audio/WorkWithAudio.o: Ping_Pong/Audio/WorkWithAudio.cpp.o
.PHONY : Ping_Pong/Audio/WorkWithAudio.o

# target to build an object file
Ping_Pong/Audio/WorkWithAudio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Audio/WorkWithAudio.cpp.o
.PHONY : Ping_Pong/Audio/WorkWithAudio.cpp.o

Ping_Pong/Audio/WorkWithAudio.i: Ping_Pong/Audio/WorkWithAudio.cpp.i
.PHONY : Ping_Pong/Audio/WorkWithAudio.i

# target to preprocess a source file
Ping_Pong/Audio/WorkWithAudio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Audio/WorkWithAudio.cpp.i
.PHONY : Ping_Pong/Audio/WorkWithAudio.cpp.i

Ping_Pong/Audio/WorkWithAudio.s: Ping_Pong/Audio/WorkWithAudio.cpp.s
.PHONY : Ping_Pong/Audio/WorkWithAudio.s

# target to generate assembly for a file
Ping_Pong/Audio/WorkWithAudio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Audio/WorkWithAudio.cpp.s
.PHONY : Ping_Pong/Audio/WorkWithAudio.cpp.s

Ping_Pong/Functions/Functions.o: Ping_Pong/Functions/Functions.cpp.o
.PHONY : Ping_Pong/Functions/Functions.o

# target to build an object file
Ping_Pong/Functions/Functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Functions/Functions.cpp.o
.PHONY : Ping_Pong/Functions/Functions.cpp.o

Ping_Pong/Functions/Functions.i: Ping_Pong/Functions/Functions.cpp.i
.PHONY : Ping_Pong/Functions/Functions.i

# target to preprocess a source file
Ping_Pong/Functions/Functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Functions/Functions.cpp.i
.PHONY : Ping_Pong/Functions/Functions.cpp.i

Ping_Pong/Functions/Functions.s: Ping_Pong/Functions/Functions.cpp.s
.PHONY : Ping_Pong/Functions/Functions.s

# target to generate assembly for a file
Ping_Pong/Functions/Functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Functions/Functions.cpp.s
.PHONY : Ping_Pong/Functions/Functions.cpp.s

Ping_Pong/Json/Json.o: Ping_Pong/Json/Json.cpp.o
.PHONY : Ping_Pong/Json/Json.o

# target to build an object file
Ping_Pong/Json/Json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Json/Json.cpp.o
.PHONY : Ping_Pong/Json/Json.cpp.o

Ping_Pong/Json/Json.i: Ping_Pong/Json/Json.cpp.i
.PHONY : Ping_Pong/Json/Json.i

# target to preprocess a source file
Ping_Pong/Json/Json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Json/Json.cpp.i
.PHONY : Ping_Pong/Json/Json.cpp.i

Ping_Pong/Json/Json.s: Ping_Pong/Json/Json.cpp.s
.PHONY : Ping_Pong/Json/Json.s

# target to generate assembly for a file
Ping_Pong/Json/Json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Json/Json.cpp.s
.PHONY : Ping_Pong/Json/Json.cpp.s

Ping_Pong/Ping_Pong.o: Ping_Pong/Ping_Pong.cpp.o
.PHONY : Ping_Pong/Ping_Pong.o

# target to build an object file
Ping_Pong/Ping_Pong.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Ping_Pong.cpp.o
.PHONY : Ping_Pong/Ping_Pong.cpp.o

Ping_Pong/Ping_Pong.i: Ping_Pong/Ping_Pong.cpp.i
.PHONY : Ping_Pong/Ping_Pong.i

# target to preprocess a source file
Ping_Pong/Ping_Pong.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Ping_Pong.cpp.i
.PHONY : Ping_Pong/Ping_Pong.cpp.i

Ping_Pong/Ping_Pong.s: Ping_Pong/Ping_Pong.cpp.s
.PHONY : Ping_Pong/Ping_Pong.s

# target to generate assembly for a file
Ping_Pong/Ping_Pong.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PingPongRelease.dir/build.make CMakeFiles/PingPongRelease.dir/Ping_Pong/Ping_Pong.cpp.s
.PHONY : Ping_Pong/Ping_Pong.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PingPongRelease"
	@echo "... Ping_Pong/Audio/WorkWithAudio.o"
	@echo "... Ping_Pong/Audio/WorkWithAudio.i"
	@echo "... Ping_Pong/Audio/WorkWithAudio.s"
	@echo "... Ping_Pong/Functions/Functions.o"
	@echo "... Ping_Pong/Functions/Functions.i"
	@echo "... Ping_Pong/Functions/Functions.s"
	@echo "... Ping_Pong/Json/Json.o"
	@echo "... Ping_Pong/Json/Json.i"
	@echo "... Ping_Pong/Json/Json.s"
	@echo "... Ping_Pong/Ping_Pong.o"
	@echo "... Ping_Pong/Ping_Pong.i"
	@echo "... Ping_Pong/Ping_Pong.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

